[tool.poetry]
name = "repl_python3_b4x2nx49b6c569w3c2x54"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"
discord = "^1.7.3"
Flask = "^2.0.1"
pytz = "^2021.1"
discord-components = "^2.1.2"
Cybernator = "^0.6.3"
discord_buttons_plugin = "^0.1.2"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
